### ISSUE TITLE
TeamCity

### ISSUE THREAD

**Issue by mikeedwards83** [sergeyshushlyapin/Sitecore.FakeDb#152]
I am having a problem running FakeDB on TeamCity. Most of the test pass but a few tests that rely on custom pipeline processes do not seem to work. Are they any know issues with FakeDB and TeamCity?

Failed tests can be seen on the Glass Build server http://build.glass.lu/

**Comment by sergeyshushlyapin** [comment]
It seems you need to reference Microsoft DI in your test project:

Test(s) failed. System.IO.FileNotFoundException : Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.
   at Sitecore.Configuration.Factory.<.cctor>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Sitecore.Configuration.Factory.GetDatabase(String name)
   at Sitecore.FakeDb.Db..ctor(String databaseName)
   at Glass.Mapper.Sc.FakeDb.ThirdParty.SimpleInjector.SimpleInjectorConstructionFixture.Execute_RequestInstanceOfClassWithServiceButLazy_ReturnsInstanceWithService() in c:\TeamCity\buildAgent\work\27e9c137daf04a9a\Tests\Unit Tests\Glass.Mapper.Sc.FakeDb.ThirdParty\SimpleInjector\SimpleConstructionFixture.cs:line 21

**Comment by mikeedwards83** [comment]
no this is a different issue, I am running tests against multiple version of SC8 and trying to tackle two problems at once. However I think it might not be a FakeDB thing, but instead how we handle determining if we are in experience editor mode. Locally everything seems ok but when we run against 81 on the server it seems to not be in experience editor mode.

**Comment by mikeedwards83** [comment]
I am closing this issue, sorry to have wasted your time.

**Comment by pveller** [comment]
A failed test did what it was designed to do. Pointed you at a bug :)
