### ISSUE TITLE
License is missing: FakeDB 1.3.3 with Sitecore 8.2 Update 1

### ISSUE THREAD

**Issue by yassinealahyane** [sergeyshushlyapin/Sitecore.FakeDb#157]
Hello,

After updating Habitat to Sitecore 8.2 Update 1 and FakeDB 1.3.3, we started having this error:

Sitecore.SecurityModel.License.LicenseException : Required license is missing: Runtime
   at Sitecore.SecurityModel.License.LicenseManager.DemandRuntime(Boolean acceptExpress, Boolean forceUpdate)
   at Sitecore.SecurityModel.License.LicenseManager.DemandRuntime(Boolean acceptExpress)
   at Sitecore.Data.Managers.DefaultItemManager.get_FallbackProvider()
   at Sitecore.Data.Managers.DefaultItemManager.<>c__DisplayClass2f.<GetItem>b__2e()
   at Sitecore.Data.Managers.DefaultItemManager.ExecuteAndReturnResult[TArgs,TResult](String pipelineName, String pipelineDomain, Func`1 pipelineArgsCreator, Func`1 fallbackResult)
   at Sitecore.Data.Managers.DefaultItemManager.GetItem(ID itemId, Language language, Version version, Database database, SecurityCheck securityCheck)
   at Sitecore.Data.Managers.DefaultItemManager.GetItem(ID itemId, Language language, Version version, Database database)
   at Sitecore.Data.Managers.ItemManager.GetItem(ID itemId, Language language, Version version, Database database)
   at Sitecore.Data.DefaultDatabase.GetItem(ID itemId)
   at Sitecore.FakeDb.Db.GetItem(ID id)
   at Sitecore.Feature.Accounts.Tests.AccountSettingsServiceTests.BuildUpSiteContext(Db db, String body, String from, String subj, ID outcomeID) in D:\w1\4a2797838d2bce22\src\feature\Accounts\tests\AccountSettingsServiceTests.cs:line 164
   at Sitecore.Feature.Accounts.Tests.AccountSettingsServiceTests.GetForgotPasswordMailTemplateShouldNotThrowExceptionWhenBodyIsEmpty(Db db) in D:\w1\4a2797838d2bce22\src\feature\Accounts\tests\AccountSettingsServiceTests.cs:line 106

Any Hints?

Thanks.

Yassine

**Comment by yassinealahyane** [comment]
Forget it, upgrade changed my config files and License path.
Thanks

**Comment by sergeyshushlyapin** [comment]
Forgotten.
