### ISSUE TITLE
Content search config in SC9 uses incorrect class name

### ISSUE THREAD

**Issue by kamsar** [sergeyshushlyapin/Sitecore.FakeDb#195]
I tried to run the [content search example](https://github.com/sergeyshushlyapin/Sitecore.FakeDb/wiki/Content-Search) under Sitecore 9, but I get the following error:

```
System.Exception : Could not resolve type name: Sitecore.ContentSearch.ProviderIndexSearchConfiguration, Sitecore.ContentSearch (method: Sitecore.Configuration.DefaultFactory.CreateType(XmlNode configNode, String[] parameters, Boolean assert)).
   at Sitecore.Diagnostics.Error.Raise(String error, String method)
   at Sitecore.Diagnostics.Error.Assert(Boolean condition, String error)
   at Sitecore.Configuration.DefaultFactory.CreateType(XmlNode configNode, String[] parameters, Boolean assert)
   at Sitecore.Configuration.DefaultFactory.CreateFromTypeName(XmlNode configNode, String[] parameters, Boolean assert)
   at Sitecore.Configuration.DefaultFactory.CreateObject(XmlNode configNode, String[] parameters, Boolean assert, IFactoryHelper helper)
   at Sitecore.Configuration.DefaultFactory.CreateObject(XmlNode configNode, String[] parameters, Boolean assert)
   at Sitecore.Configuration.DefaultFactory.CreateObject(String configPath, String[] parameters, Boolean assert)
   at Sitecore.ContentSearch.ContentSearchManager.get_SearchConfiguration()
```

Looking at the `Sitecore.config` for FakeDb, it looks like it's using an older class name; in SC9 the type name appears to be `Sitecore.ContentSearch.ContentSearchConfiguration, Sitecore.ContentSearch` instead.

I tried using a [config patch](https://github.com/sergeyshushlyapin/Sitecore.FakeDb/wiki/Configuration#adding-include-files-to-a-project) to change it, however it made no difference: 

```
<?xml version="1.0" encoding="utf-8" ?>
<configuration xmlns:patch="http://www.sitecore.net/xmlconfig/">
    <sitecore>
        <contentSearch>
            <configuration type="Sitecore.ContentSearch.ContentSearchConfiguration, Sitecore.ContentSearch">
                
            </configuration>
        </contentSearch>
    </sitecore>
</configuration>
```

It is possible that my patch is misauthored, however as there's no showconfig-type tool that I'm aware of for FakeDb. As well, in my .NET-core-style csproj the output path is now `bin\debug\net462` instead of just `bin\debug`. I tried putting the `App_Config` into the bin, to simulate a traditional output path, but it did not help.

**Comment by michaelthyregod** [comment]
Just a note @kamsar - Seeting AppendTargetFrameworkToOutputPath to false in your csproj files might help you to get rid of the new output folder format and get back to bin\debug as output folder.(be aware of the casing in VS2017 csproj format)

**Comment by kamsar** [comment]
@michaelthyregod thanks for the tip. That simplifies other parts of what I'm working on, but unfortunately seems to make no difference to this issue :(

**Comment by kamsar** [comment]
I suspect the root cause of this issue is right here, that this class name is different in Sitecore 9.x:

https://github.com/sergeyshushlyapin/Sitecore.FakeDb/blob/master/src/Sitecore.FakeDb/Sitecore.config#L179

**Comment by sergeyshushlyapin** [comment]
The `ContentSearchConfiguration` class should be used instead of the obsolete `Sitecore.ContentSearch.ProviderIndexSearchConfiguration` class. It works fine for all the supported Sitecore versions, so I'll release an update for that.
