### ISSUE TITLE
Issue with Sitecore 9

### ISSUE THREAD

**Issue by davidnguyen** [sergeyshushlyapin/Sitecore.FakeDb#204]
Hi Sergey,

I'm trying Sitecore.FakeDb via NuGet v2.0.0-beta2 with Sitecore 9 update 3 and getting the following exception when trying to get the simplest test to work.
`System.NullReferenceException: Object reference not set to an instance of an object.`
`Result StackTrace:	
at Sitecore.Configuration.DefaultFactory.CreateType(XmlNode configNode, String[] parameters, Boolean assert)
   at Sitecore.Configuration.DefaultFactory.CreateFromTypeName(XmlNode configNode, String[] parameters, Boolean assert)
   at Sitecore.Configuration.DefaultFactory.CreateObject(XmlNode configNode, String[] parameters, Boolean assert, IFactoryHelper helper)
   at Sitecore.Configuration.DefaultFactory.CreateObject(XmlNode configNode, String[] parameters, Boolean assert)
   at Sitecore.Configuration.DefaultFactory.CreateObject(String configPath, String[] parameters, Boolean assert)
   at Sitecore.Configuration.DefaultFactory.CreateObject(String configPath, Boolean assert)
   at Sitecore.Configuration.DefaultFactory.GetDatabase(String name, Boolean assert)
   at Sitecore.Configuration.DefaultFactory.GetDatabase(String name)
   at Sitecore.Configuration.Factory.GetDatabase(String name)
   at Sitecore.Data.Database.GetDatabase(String databaseName)
   at Sitecore.FakeDb.Db..ctor(String databaseName)`

My app.config file has databaseType set to "Sitecore.Data.**DefaultDatabase**, Sitecore.Kernel" with the license file in place.

I can't seem to workout why at the moment, any secrete sauce I have to put in to make it tick with Sitecore 9?

Thanks

**Comment by sergeyshushlyapin** [comment]
Hi David,

Sitecore 9 Update 3?! I haven't seen that before... At least it's not publicly available yet.
https://dev.sitecore.net/Downloads/Sitecore_Experience_Platform.aspx

**Comment by mikeedwards83** [comment]
I am having the same problem with Sitecore 9.1

**Comment by mikeedwards83** [comment]
Hum interestingly the config in memory is:

  <database id=\"master\" type=\"Sitecore.Data.Database, Sitecore.Kernel\" singleInstance=\"true\">
      <param desc=\"name\">$(id)</param>
      <dataProviders hint=\"list:AddDataProvider\">
        <dataProvider ref=\"dataProviders/main\" />
        <dataProvider ref=\"dataProviders/language\" />
      </dataProviders>
    </database>

It seems that the DB type is not being updated based on the DB Type specified in the App.config.

**Comment by mikeedwards83** [comment]
Gah, the test runner wasn't copying the new App.config across after it had been changed. So the change of the DB type was not being picked up!
