### ISSUE TITLE
Exception when trying to retrieve BaseTemplates

### ISSUE THREAD

**Issue by PatrickDelancy** [sergeyshushlyapin/Sitecore.FakeDb#67]
I haven't dug into the code to troubleshoot this very much, but I thought I would get it out there in case there's an obvious fix you can see.

It seems that I cannot retrieve BaseTemplates:
```cs
using (var db = new Db() {new DbItem("page")})
{
  var page = db.GetItem("/sitecore/content/page");
  var baseTemplates = page.Template.BaseTemplates;
  Assert.NotNull(baseTemplates);
}
```

Get this exception every time. I have tried specifying a fake template, using a common template that FakeDb builds automatically (like Folder).
```
System.ArgumentNullException : Value cannot be null.
Parameter name: itemId
   at Sitecore.Diagnostics.Assert.ArgumentNotNull(Object argument, String argumentName)
   at Sitecore.FakeDb.Data.Engines.DataStorage.GetSitecoreItem(ID itemId, Language language, Version version) 
   at Sitecore.FakeDb.Data.Engines.DataStorage.GetSitecoreItem(ID itemId, Language language)
   at Sitecore.FakeDb.Data.Engines.DataCommands.GetParentCommand.DoExecute() 
   at Sitecore.Data.Engines.EngineCommand`2.Execute()
   at Sitecore.Data.Managers.ItemProvider.GetParent(Item item)
   at Sitecore.Data.Managers.ItemProvider.GetParent(Item item, SecurityCheck securityCheck)
   at Sitecore.Security.AccessControl.ItemAuthorizationHelper.GetAncestorAccess(Item item, Account account, AccessRight accessRight, PropagationType propagationType)
   at Sitecore.Security.AccessControl.ItemAuthorizationHelper.GetItemAccess(Item item, Account account, AccessRight accessRight, PropagationType propagationType)
   at Sitecore.Security.AccessControl.ItemAuthorizationHelper.GetAccess(Item item, Account account, AccessRight accessRight)
   at Sitecore.FakeDb.Security.AccessControl.FakeAuthorizationProvider.GetAccessCore(ISecurable entity, Account account, AccessRight accessRight)
   at Sitecore.Security.AccessControl.AuthorizationProvider.GetAccess(ISecurable entity, Account account, AccessRight accessRight)
   at Sitecore.FakeDb.Security.AccessControl.FakeAuthorizationProvider.GetAccess(ISecurable entity, Account account, AccessRight accessRight)
   at Sitecore.Security.AccessControl.AuthorizationManager.IsAllowed(ISecurable entity, AccessRight right, Account account)
   at Sitecore.Data.Managers.ItemProvider.ApplySecurity(Item item, SecurityCheck securityCheck)
   at Sitecore.Data.Managers.ItemManager.GetItem(ID itemId, Language language, Version version, Database database)
   at Sitecore.Data.TemplateRecords.GetTemplate(ID templateID, Language language)
   at Sitecore.Data.Items.TemplateItem.get_BaseTemplates()
```

**Comment by sergeyshushlyapin** [comment]
Fixed.

**Comment by sergeyshushlyapin** [comment]
Published on [Nuget](https://www.nuget.org/packages/Sitecore.FakeDb/) as v0.27.2
