### ISSUE TITLE
Calling item.Recycle() results in missing config node exception

### ISSUE THREAD

**Issue by kamsar** [sergeyshushlyapin/Sitecore.FakeDb#83]
If you create a fakedb item and then call `Recycle()` on it, you will receive the following exception:

```
System.InvalidOperationException : Could not find configuration node: archives
   at Sitecore.Configuration.Factory.GetConfigNode(String xpath, Boolean assert)
   at Sitecore.Configuration.Factory.GetProviders(String rootPath, ref TProvider defaultProvider)
   at Sitecore.Configuration.ProviderHelper`2.ReadProviders()
   at Sitecore.Configuration.ProviderHelper`2.get_Provider()
   at Sitecore.Data.Items.Item.Recycle()
   at Rainbow.Storage.Sc.SitecoreDataStore.Remove(IItemData item) in SitecoreDataStore.cs: line 124
   at Rainbow.Storage.Sc.Tests.SitecoreDataStoreTests.Remove_RemovesExpectedItem() in SitecoreDataStoreTests.cs: line 157
```

I was able to resolve the issue by adding the archives section from the Sitecore web.config to the app.config (even without actually configuring the SQL db, merely having the nodes was sufficient):

```
<archives defaultProvider="sql" enabled="true">
	<providers>
		<clear />
		<add name="sql" type="Sitecore.Data.Archiving.SqlArchiveProvider, Sitecore.Kernel" database="*" />
	</providers>
</archives>
```

**Comment by sergeyshushlyapin** [comment]
Fixed and released as v0.29.3. Thanks!
